### ISSUE TITLE
Service newrelic-infra still is wrongly being checked

### ISSUE THREAD

**Issue by AgusBarra** [newrelic/infrastructure-agent-puppet#11]
Service newrelic-infra still is wrongly being checked
Basically, if you choose Class newrelic-infra , ensure => absent (to uninstall package)
it works fine, but service new relic is still  being checked to be running after removed the entire package

obviously service will not exists after uninstalling package.

Please fix this !
related to this line:
https://github.com/newrelic/infrastructure-agent-puppet/blob/master/manifests/agent.pp#L124

**Comment by smith** [comment]
@AgusBarra would #14 fix this?

**Comment by AgusBarra** [comment]
@smith yes it will.
WE were pushing a ensure absent to uninstall service in some nodes, but was still checking service to running, with FIX #14 , there will be a new variable . so my jobs needs to add that to ensure_service stopped, but will avoid dodgy failures as 2 variables better than 1 to manage this.
Cheers!

**Comment by AgusBarra** [comment]
@smith   Could this be merged soon , by any chance ?
Regards
Agus.

**Comment by smith** [comment]
@AgusBarra I've requested changes on #14 because I had a suggestion and some trouble running it in the development environment. Any chance you could try to run it locally (on CentOS 6) and see if you have any problems?

**Comment by AgusBarra** [comment]
Tested on centos 6.9 , seems fine by my testing...
Changed puppet configs to change service status, and it works

**Comment by AgusBarra** [comment]
@smith wanna marge this please so we can pushed this change into our prod next week ?

**Comment by AgusBarra** [comment]
also if possible merge https://github.com/newrelic/infrastructure-agent-puppet/pull/10

**Comment by smith** [comment]
Fixed in #14.
