### ISSUE TITLE
Needs to default to upstart for rhel6 as well

### ISSUE THREAD

**Issue by cyberious** [newrelic/infrastructure-agent-puppet#13]
Current default for Puppet Service provider on RedHat Enterprise is chkconfig and service https://docs.puppet.com/puppet/latest/types/service.html#service-provider-redhat and instead needs to be updated to use upstart as well. #10 is already to do this in part but should be expanded to do all of osfamily redhat

**Comment by smith** [comment]
#10 is merged and should fix the problem. Would love to have a PR to make the check use `osfamily` if you get the time.

**Comment by adastidar** [comment]
@smith This issue got regressed in a subsequent merge commit(f94fe69c077bcde3a74d7331098382d7f3575f4e). Could you re-open this issue and add the fix back?

**Comment by smith** [comment]
@adastidar the current version seems to already have this:

https://github.com/newrelic/infrastructure-agent-puppet/blob/86c228ff18d1923d34644dcec6f427bb4e722ef6/manifests/agent.pp#L144-L153

It may have been an issue with the agent package. Could you try again with the latest agent release?

**Comment by adastidar** [comment]
The fix is to use the `upstart` provider for el6 instead of `sbin`.  #10 had the fix. #14 reverted it.

**Comment by smith** [comment]
Oh I see. Thanks will fix.
