### ISSUE TITLE
Ubuntu 20.04 support?

### ISSUE THREAD

**Issue by xandrellas** [newrelic/infrastructure-agent-puppet#133]
Please see link to github gist : https://gist.github.com/xandrellas/a30fcfc5bd2d307260dd752e1385668e

This is on a fresh vagrant ubuntu 20.04 host, running puppet agent 6.25.1, puppetserver 6.17.1, all packages updated/upgraded, kernel version 5.4.0-91-generic.

Host is idempotent after 2 puppet runs, but this is obviously problematic.

**Comment by Hans-Maulwurf** [comment]
Are there any plans to officially support Ubuntu 20.04 soon? 22.04 LTS is there for quite a while too

**Comment by davidgit** [comment]
Hi @xandrellas, @Hans-Maulwurf 

I don't have a solution for you for this, but we're building a new one. You can find the details here: https://github.com/newrelic/puppet-install

Would love to hear your thoughts.

Thanks
