### ISSUE TITLE
How could you support an OS that does not exist (yet)

### ISSUE THREAD

**Issue by noqqe** [newrelic/infrastructure-agent-puppet#2]
In Readme you describe you also support Debian9 and Debian10. 

In metadata.json is only Debian 7. 

Please streamline what you plan to support.

**Comment by mihasya** [comment]
It does look like we got a bit over-enthused with that portion of the README. I'll work on a match to fix that as well as the metadata section. In the meantime, you can check our documentation to see what is supported: https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/getting-started/compatibility-requirements-new-relic-infrastructure#operating-systems

Thanks!

**Comment by mihasya** [comment]
This was fixed with #3
