### ISSUE TITLE
Configuration option selinux_enable_semodule not supported

### ISSUE THREAD

**Issue by irfanypatel** [newrelic/infrastructure-agent-puppet#27]
As of Agent 1.0.872, the following Improvement has been introduced:

> Allow disabling inventory of SELinux modules in hosts where the associated command consumes too much CPU. Set selinux_enable_semodule configuration option to false to disable it while keeping the rest of SELinux plugin features.
https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-10872 

This module should support this configuration, considering it's importance on usability of newrelic-infra, see: https://discuss.newrelic.com/t/newrelic-infra-agent-is-launching-semodule-l-over-and-over-again-killing-the-box/50619/25

**Comment by smith** [comment]
The best way to handle this is to make this module do what the Chef and Ansible ones already do, which is having a generic config hash that can get serialized to yaml and create the config file. This will make it so all options supported in the configuration file will work and we won't need to make changes when new ones are added.

A pull request that makes this change would be very welcome, and if that doesn't happen we will get adding this as time allows.

**Comment by irfanypatel** [comment]
PR #28 created to support custom configuration options.

**Comment by smith** [comment]
Fixed in #28.
