### ISSUE TITLE
Ensure latest causes failures on ubuntu 12.04

### ISSUE THREAD

**Issue by becomingwisest** [newrelic/infrastructure-agent-puppet#29]
TLDR: The post install in 1.0.912 and some earlier packages doesn't handle upgrades if the agent is already running. The default should be change to installed, or the package needs to try restarting the service too.

The /var/lib/dpkg/info/newrelic-infra.postinst is

> #!/bin/sh
> 
> if [ -e "/etc/init/newrelic-infra.conf" ]; then
> 	initctl start newrelic-infra || exit $?
> fi

And http://manpages.ubuntu.com/manpages/precise/man8/initctl.8.html states that:

> If the job is already running, start will return an error.

This gives apt errors:

> Setting up newrelic-infra (1.0.909) ... 
> initctl: Job is already running: newrelic-infra 
> dpkg: error processing newrelic-infra (--configure): 
> subprocess installed post-installation script returned error exit status 1 
> Errors were encountered while processing: 
> newrelic-infra 
> E: Sub-process /usr/bin/dpkg returned an error code (1)

Example in the community are seen at the bottom of https://discuss.newrelic.com/t/upgrading-the-agent-fails-to-restart-properly-on-ubuntu/42840/6

**Comment by xino12** [comment]
Hi, we've submitted a patch to it fixes this issue.

Thanks for reporting it, it will be available in the next version of the agent.
