### ISSUE TITLE
Difference between custom attributes and custom configs?

### ISSUE THREAD

**Issue by kwstone14** [newrelic/infrastructure-agent-puppet#38]
There are provisions in this module for both custom attributes and "custom configs". It's the custom configs section that I can't make sense of, as I can't find any documentation at Newrelic that says what it is. There are only comments in agent.pp that says that it references configuration directives that aren't explicitly exposed.

Two attributes that I'm interested in are event_queue_depth and network_interface_filters. References to those two were tucked into release notes as opposed to the main documentation. We are using these two attributes, but there's nothing in this module that references them; they aren't parameters in agent.pp. 

Are these fields examples of things that should go into custom_configs? Or should I fork the module and submit a pull request to add those fields?

**Comment by alejandrodnm** [comment]
Hello @kwstone14, `event_queue_depth` and `network_interface_filters` should be passed as `custom_config`. Let me try to clarify the difference: 

## Custom Attributes ##

From the [New Relic Infrastructure Docs](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/configuration/configure-infrastructure-agent#attributes) 

> Custom attributes are key-value pairs (similar to tags in other tools) used to annotate the data from the Infrastructure agent. You can use this metadata to build filter sets, group your results, and annotate your Insights data. For example, you might indicate a machine's environment (staging or production), the service a machine hosts (login service, for example), or the team responsible for that machine.

Basically custom attributes are tags or metadata that the agents applies to the metrics it sends.

## Custom Configs

In this case refers to the configuration options you can set for the agent. They are documented [here](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/configuration/configure-infrastructure-agent#general), keep in mind that this list is not complete, but we have some tasks to improve and document all the config options. 

This config options can also be set via [environment variables](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/configuration/configure-infrastructure-agent#Environment_Variables), or passed through flags to the binary, Ex: `newrelic-infra -verbose 1`

I'll close this issue. but If I wasn't clear or you have more questions, let us know and we'll reopen it.

Cheers.
