### ISSUE TITLE
Can't apply the module in an Amazon Linux instance

### ISSUE THREAD

**Issue by ramonPires** [newrelic/infrastructure-agent-puppet#4]
I think there is a problem with these 2 lines : https://github.com/newrelic/infrastructure-agent-puppet/blob/master/manifests/agent.pp#L76 and https://github.com/newrelic/infrastructure-agent-puppet/blob/master/manifests/agent.pp#L104 .  
```
[ec2-user@machine ~]$ facter operatingsystem operatingsystemmajrelease  operatingsystemrelease
operatingsystem => Amazon
operatingsystemmajrelease => 4
operatingsystemrelease => 4.4.23-31.54.amzn1.x86_64
[ec2-user@machine ~]$ facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "Amazon",
  release => {
    full => "4.4.23-31.54.amzn1.x86_64",
    major => "4",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}
```
In the first line the `$operatingsystemmajrelease` variable is used to define the version of system, but in the manual installation if you need to configure the Amazon Linux, CentOS 6 and RHEL 6  yum repository, you need to specify version `6`, as we can see here https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/installation/install-infrastructure-linux#el6-add-repo, in my case the value  that I  got from the `operatingsystemmajrelease` was `4`, and this repository https://download.newrelic.com/infrastructure_agent/linux/yum/el/4/x86_64/newrelic-infra.repo don't exist. 

In the second line, the condition check if `$::operatingsystemmajrelease` are equals to `2015`, the problem is similar to the first line, the variable `operatingsystemmajrelease` return `4` ,so the block: 
```
service { 'newrelic-infra':
      ensure => 'running',
      provider => 'upstart',
      require => Package['newrelic-infra'],
   }
```
will never be executed, occasioning some errors.

The AMI:  ami-97831ffb
![image](https://cloud.githubusercontent.com/assets/1796577/22021554/2124c9cc-dca5-11e6-92f6-4590e2bef8a3.png)

**Comment by mihasya** [comment]
@ramonPires thank you so much for the report! Can you confirm that `upstart` is available in that version of AWS Linux? The output of `which initctl` should be sufficient. Once that's confirmed, I can work up a patch that will fix these issues.

**Comment by ramonPires** [comment]
@mihasya :
```
[ec2-user@machine ~]$ which initctl
/sbin/initctl
```

**Comment by mihasya** [comment]
👌

**Comment by mihasya** [comment]
@ramonPires I don't have an easy way to test this on an AWS machine. Are you able to run a branch of the code on one of your machines to verify the fix? The branch is `fix_aws`. If you can't, I will try to find time to configure Kitchen to run an AWS instance. Thanks.

**Comment by ramonPires** [comment]
@mihasya I will test your branch soon as possible

**Comment by ramonPires** [comment]
@mihasya your fix is working, you can merge to the master.

**Comment by mihasya** [comment]
👍  thank you so much for the detailed but report and for the quick responses. Going to bump version and merge.
