### ISSUE TITLE
Problems with Yum Repo newrelic_infra-agent

### ISSUE THREAD

**Issue by rmeffan** [newrelic/infrastructure-agent-puppet#42]
Hi,

I have implemented the NR infrastructure agent puppet module v0.7.1 in our org, but it's throwing errors that appear to be related to an inability to automatically import the repo GPG key. If I run `yum info newrelic-infra` on the host after the puppet agent runs, I am prompted to manually import the key. If I respond with 'y', the key imports, and the module works properly from that point on.

Is this the expected behavior for the out-of-box configuration for this module?

Thanks,

-Rob

**Comment by rmeffan** [comment]
Wrong button. Whoops. Long week.

**Comment by rmeffan** [comment]
```
puppet-agent[31816]: (/Stage[main]/Newrelic_infra::Agent/Package[newrelic-infra]/ensure) https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for newrelic_infra-agent```

**Comment by alejandrodnm** [comment]
Hi @rmeffan we'll take a look at it and let you know. Cheers.

**Comment by alejandrodnm** [comment]
Hi @rmeffan can you show the content of 

`cat /etc/yum.repos.d/newrelic_infra-agent.repo`

and the result of 

`rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep newrelic`

Thanks

**Comment by alejandrodnm** [comment]
Hi @rmeffan I'm going to close the issue, but feel free to reopen it or continue the discussion here.

Cheers.
