### ISSUE TITLE
Using Hiera?

### ISSUE THREAD

**Issue by xandrellas** [newrelic/infrastructure-agent-puppet#49]
Using Hiera as an ENC, I'd like to be able to override/allocate data such as license key into this module.

looking at : 
class newrelic_infra::agent (
  $ensure               = 'latest',
  $service_ensure       = 'running',
  $license_key          = '',
....

I should be able to override via Hiera using:
newrelic_infra::agent:license_key: '12345'
But when I run puppet agent I get an evaluating function error as New Relic license key not provided.

I'm able to easily handle this via other classes using similar methodologies.  No Hiera.yaml is defined at the module level for those modules either.

Thoughts?  Newer to puppet so maybe I am missing a key aspect.

**Comment by jcwarp** [comment]
You only have one colon between agent and lincense_key

**Comment by xandrellas** [comment]
Thank you for the clarification.  Works great.
