### ISSUE TITLE
Support proxied repos

### ISSUE THREAD

**Issue by gepandz** [newrelic/infrastructure-agent-puppet#53]
Hi! We have security rules that do not allow our servers to dial out and install software from external sites, only from internal proxies like Artifactory, RH Satellite, or Pulp, so this code can't run on our systems, as the code hard-codes download.newrelic.com.

Is it feasible to allow the source of the RPMs or tarballs to be parameters passed into the `::agent` class? We have an in-house module that looks similar, so we can keep using that; thus, this isn't a critical time-sensitive issue. I also understand if NR doesn't want to support side-loads of their software from other sources for security or supportability reasons...

Thanks!

Digitally yours,
George Pandzik

**Comment by davidbrota** [comment]
Hi George,

Your proposal sounds reasonable and we also support it, but it's not in our immediate plans to develop it.
We'll gladly accept a PR with the changes and we'll review and merge them.

Regards,
David

**Comment by JakubKotkowiak** [comment]
A fix for this issue has been included in the following PR:
https://github.com/newrelic/infrastructure-agent-puppet/pull/80
