### ISSUE TITLE
No longer works in Puppet 3.8

### ISSUE THREAD

**Issue by StuWhitby** [newrelic/infrastructure-agent-puppet#59]
Compatability for this module states: Puppet >= 3.0.0 < 6.0.0

However, that doesn't seem to fit with this section of agent.pp:

          case $facts['os']['architecture'] {
            "x86_64": { $arch = 'amd64' }
            "i386": { $arch = '386' }
            default: { $arch = facts['os']['architecture'] }
          }

I believe, as per https://puppet.com/docs/facter/3.9/core_facts.html, that ['os']['architecture'] isn't supported before facter 3.9.  Prior to that it's just ['architecture'].

I'm entirely prepared to be wrong as I'm reasonably new to Puppet, but this fails for me in Puppet 3.8 with: 

Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at '['; expected ']' at /etc/puppet/environments/newrelic_infra2/modules/newrelic_infra/manifests/agent.pp:190 on node ***********.********.com

**Comment by mariomac** [comment]
Hi @StuWhitby, thank you for reporting the issue. I have create a ticket to be internally handled by the engineering team.

**Comment by ardias** [comment]
Hi @StuWhitby  We've just released a backcompat version that works in puppet => 3.4 in Ubuntu => 14.05 <= 16.04
https://github.com/newrelic/infrastructure-agent-puppet/releases/tag/0.10.0-legacy

Install with : puppet module install newrelic-newrelic_infra --version 0.10.0-legacy

We'll release a fixed version with the proper requirements later on.
Please let us know if this works for you

**Comment by joshuaaguilar20** [comment]
Just wanted to leave a thank you!!!! this legacy post is perfect!. If anyone is struggling with error:

```bash
Syntax error at '['; expected ']' 
```
@StuWhitby  advice was spot on. The legacy agent file provided in the link above resolved my issue.The os[arch] indeed was the issue. This works with puppetNG confirmed 3.2/3.3


legacy agent repo: [https://github.com/newrelic/infrastructure-agent-puppet/releases/tag/0.10.0-legacy]

Thanks again for the post.
