### ISSUE TITLE
Support for NRIA_MODE (ie. running as unprivileged user)

### ISSUE THREAD

**Issue by Jayfrown** [newrelic/infrastructure-agent-puppet#60]
The documentation [here](https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure/linux-installation/install-infrastructure-linux-using-package-manager#install-unprivileged) provides a means to manually install the New Relic Infrastructure Agent to run as an unprivileged user, by using environment variables when calling yum.

This functionality seems to be missing from this puppet module. I would like to be able to use this puppet module to install New Relic Infrastructure across our entire fleet, while refraining from running the agent as root. 

AFAICT there is no mention of a configuration statement that does this.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
