### ISSUE TITLE
Bad target hash error

### ISSUE THREAD

**Issue by tadayoni1** [newrelic/infrastructure-agent-puppet#61]
I have issues getting newrelic-infra installed using puppet 3.7.4 on Ubuntu 14.04. I tried 

- 0.9.0 tag: https://github.com/newrelic/infrastructure-agent-puppet/tree/0.9.0
    - Error: "facts is not a hash or array when accessing it with kernel"
- 0.8.3 tag: https://github.com/newrelic/infrastructure-agent-puppet/tree/0.8.3
    - Error: "Error: regsubst(): bad target hash:`{"ID"=>"A758B3FBCD43BE8D123A3476BB29EE038ECCE87C", "SOURCE"=>"HTTPS://DOWNLOAD.NEWRELIC.COM/INFRASTRUCTURE_AGENT/GPG/NEWRELIC-INFRA.GPG"}' at /etc/puppet/modules/apt/manifests/key.pp:14"

Does this repo support Puppet 3 and ubuntu 14?

**Comment by ardias** [comment]
Hi @tadayoni1 Ubuntu 14 and Puppet 3 should be supported. We'll try to reproduce the issue

**Comment by ardias** [comment]
Hi @tadayoni1 We've just released a backcompat version that works in puppet => 3.4 in Ubuntu 14.05.
https://github.com/newrelic/infrastructure-agent-puppet/releases/tag/0.10.0-legacy

Install with : `puppet module install newrelic-newrelic_infra --version 0.10.0-legacy`

**Comment by tadayoni1** [comment]
The issue turned out to be the older version of puppetlabs-apt we use. We decided to bypass apt::source and add sources with bash until we upgrade.
```
              exec { 'enable-nr-gpg-key':
                command => 'curl -s https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -',
                creates => '/etc/apt/sources.list.d/newrelic-infra.list',
                notify  => Exec['newrelic_infra-agent'],
              }
              exec { 'newrelic_infra-agent':
                command     => 'printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt trusty main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list',
                creates     => '/etc/apt/sources.list.d/newrelic-infra.list',
                require     => Package['apt-transport-https'],
                refreshonly => true,
              }
```
