### ISSUE TITLE
Agent always installs on Windows irrespective of flag

### ISSUE THREAD

**Issue by ciranor** [newrelic/infrastructure-agent-puppet#75]
The agent class, on Windows, will always install the software package, whether you've set 'absent' or 'present'.

## Description
The class newrelic_infra::agent has an "ensure" parameter, with a descriptive comment of "('absent' will uninstall)". On Linux, the various linux_providers all handle this, (in conjunction with "package_repo_ensure" to mean that an appropriate repo is set up or removed), and the package install will do whatever the "$ensure" flag indicates, whether it's latest, absent or a specific version.

On Windows, however, it's hardcoded that the package "newrelic-infra" should always be "installed" (line #243) if the agent class is called, irrespective of the "ensure" parameter.

## Expected Behavior
I would expect that "ensure", if set to "absent", would either uninstall the package on Windows if it was already present, or not install it if it wasn't already present. I would *not* expect it to install the package when set to "absent".

## Your Environment
Running puppet forge module 0.10.0, against servers running Windows.

**Comment by maju6406** [comment]
@binford2k @tspeigner this should be 'installed' should be $ensure, right? https://github.com/newrelic/infrastructure-agent-puppet/blob/master/manifests/agent.pp#L243

**Comment by binford2k** [comment]
@maju6406 at a quick skim, yes. I would think that it should match the other package resources, like https://github.com/newrelic/infrastructure-agent-puppet/blob/3e7d30c9c86a73ef0eb8c3671edebae9ef16c021/manifests/agent.pp#L142

**Comment by varas** [comment]
It should be good now, thanks!
