### ISSUE TITLE
manage_repo: false

### ISSUE THREAD

**Issue by cdenneen** [newrelic/infrastructure-agent-puppet#93]
When setting `newrelic_infra::agent::package_repo_ensure: 'absent'` it will remove any repo with that name even if goal was to use the same name but provide a mirror.
Should have a `manage_repo` `Boolean` as wrapper to attempt to create these sources or not.

Guessing manage_repo: should default to true and be required to opt-out by setting to false?

**Comment by cdenneen** [comment]
@AnnaParot @JakubKotkowiak if you could review and provide feedback I would appreciate it.

**Comment by cdenneen** [comment]
> Hello @cdenneen thanks for taking the time to report the issue and prepare a PR. We will take a look at it soon

Thanks it’s currently a blocker for us because it’s causing a duplicate declaration error for us since we are managing the repo using same name but pointing at our mirror. 

I didn’t see any spec testing for this module so I didn’t add any test for the manage_repo Boolean.

**Comment by cdenneen** [comment]
@JakubKotkowiak let me know how your review makes out. would rather get this merged than introduce a fork to my users. Thanks

**Comment by JakubKotkowiak** [comment]
Hello @cdenneen, it looks good to me. But before merging we still have to wait for another reviewer from NewRelic. As soon as we merge it we should be able to create a release containing these changes.

**Comment by cdenneen** [comment]
@JakubKotkowiak @AnnaParot can I get a status on this?

**Comment by JakubKotkowiak** [comment]
@cdenneen We're awaiting feedback from the second reviewer. We can't merge it without this. As soon as we merge and release I can post an update here for you, if that's ok?
